name: Action test run

on:
  workflow_dispatch:

jobs:
  runTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run BugBug sample test
        uses: ./ # Uses an action in the root directory
        with:
          apiToken: ${{ secrets.API_TOKEN }}
          runType: test
          variables: |
            {
              "variable1": "value1",
              "variable2": "value2"
            }
          debug: true
